"""Paperless-ngx API client — shared across all modules."""

from doc_intelligence_hub.core.paperless.client import (
    PaperlessClient,
    ProgressCallback,
    load_fixture,
)
from doc_intelligence_hub.core.paperless.metadata import (
    PAPERLESS_METADATA_REGISTRY,
    MetadataConflict,
    MetadataCreatePolicy,
    MetadataDiagnostic,
    MetadataDiagnosticCode,
    MetadataFieldKey,
    MetadataFieldSpec,
    MetadataNormalization,
    MetadataProjectionPolicy,
    MetadataSchemaError,
    MetadataSensitivity,
    MetadataValueError,
    MetadataWritePolicy,
    PaperlessFieldType,
    PaperlessMetadataResolver,
    ResolvedMetadataField,
    ResolvedMetadataSchema,
    ResolvedMetadataValue,
    build_metadata_update,
    get_metadata_field_spec,
    resolve_metadata_schema,
    resolve_metadata_value,
)

__all__ = [
    "PAPERLESS_METADATA_REGISTRY",
    "MetadataConflict",
    "MetadataCreatePolicy",
    "MetadataDiagnostic",
    "MetadataDiagnosticCode",
    "MetadataFieldKey",
    "MetadataFieldSpec",
    "MetadataNormalization",
    "MetadataProjectionPolicy",
    "MetadataSchemaError",
    "MetadataSensitivity",
    "MetadataValueError",
    "MetadataWritePolicy",
    "PaperlessClient",
    "PaperlessFieldType",
    "PaperlessMetadataResolver",
    "ProgressCallback",
    "ResolvedMetadataField",
    "ResolvedMetadataSchema",
    "ResolvedMetadataValue",
    "build_metadata_update",
    "get_metadata_field_spec",
    "load_fixture",
    "resolve_metadata_schema",
    "resolve_metadata_value",
]
