const node = ({
    id,
    label,
    lens,
    kind,
    parent = null,
    status = "active",
    summary,
    details,
    paths = [],
    tags = [],
    system = "OWL",
    stores = [],
}) => ({
    id,
    label,
    lens,
    kind,
    parent,
    status,
    summary,
    details,
    paths,
    tags,
    system,
    stores,
});

const store = (system, role, location, details) => ({ system, role, location, details });

export const graph = {
    version: 1,
    title: "OWL current and planned system map",
    description: "Three connected lenses over OWL capabilities, architecture, entities, storage, and external ownership.",
    assessedAt: "2026-08-24",
    assessmentNotes: [
        "Implementation and tests take precedence over older assessment documents when they conflict.",
        "Correspondent intelligence is marked partial because substantial code exists while rollout and Tyrion reconciliation remain incomplete.",
        "Planned nodes describe open issues or implementation-ready designs, not shipped behavior.",
    ],
    nodes: [
        node({
            id: "capabilities",
            label: "OWL Capabilities",
            lens: "feature",
            kind: "root",
            summary: "Organize, Watch, Learn: document intelligence and human-in-the-loop workflows around Paperless-ngx.",
            details: "This lens separates currently operating capabilities from partial integrations, planned delivery, and design-only concepts. Status is based on code, tests, current issues, and the newest roadmap evidence.",
            paths: ["docs/feature-roadmap.md", "docs/architecture/index.md", "README.md"],
            tags: ["product", "current-state", "roadmap"],
        }),
        node({
            id: "document-operations",
            label: "Document Operations",
            lens: "feature",
            kind: "area",
            parent: "capabilities",
            summary: "Operational pipelines that classify, group, match, and enrich documents.",
            details: "These are OWL's mature domain workflows. Each owns an API surface, business logic, persistence, and direct UI or review surface.",
            paths: ["src/doc_intelligence_hub/modules/"],
            tags: ["pipelines"],
        }),
        node({
            id: "action-queue",
            label: "Action Queue",
            lens: "feature",
            kind: "capability",
            parent: "document-operations",
            summary: "Classifies documents into recommended real-world actions and tracks their lifecycle.",
            details: "The fetch, classify, store, and enrich pipeline supports PAY, RESPOND, FILE, REVIEW, SHARE, SCHEDULE, SIGN, ARCHIVE, and TASK. It includes fallback analysis, risk and reasoning display, lifecycle APIs, Paperless-aware write-back, and Mission Control reconciliation.",
            paths: [
                "src/doc_intelligence_hub/modules/action_queue/",
                "src/doc_intelligence_hub/api/routers/action_queue.py",
                "frontend/src/pages/ActionQueue.tsx",
                "docs/guide/action-queue-guide.md",
            ],
            tags: ["tasks", "classification", "paperless"],
            stores: [
                store("OWL", "system of record", "/app/data/action_queue.db", "Actions, feedback, processing history, and queue configuration."),
                store("Paperless-ngx", "document and metadata authority", "Paperless documents, tags, and custom fields", "Source document and configured status/enrichment metadata."),
                store("Mission Control", "projection and work surface", "Document Intelligence connector projection", "Mirrors bounded action lifecycle data; OWL remains source authority."),
            ],
        }),
        node({
            id: "statement-tracking",
            label: "Statement Tracking",
            lens: "feature",
            kind: "capability",
            parent: "document-operations",
            summary: "Discovers recurring document series, infers cadence, detects gaps, and recommends follow-up.",
            details: "Provider discovery, monthly/quarterly/annual recurrence, configurable grace periods, series curation, split/merge, and missing-statement recommendations are implemented against live Paperless data.",
            paths: [
                "src/doc_intelligence_hub/modules/statements/",
                "src/doc_intelligence_hub/api/routers/statements.py",
                "frontend/src/pages/Statements.tsx",
                "docs/guide/statement-tracking-guide.md",
            ],
            tags: ["recurrence", "series", "gaps"],
            stores: [
                store("OWL", "system of record", "/app/data/statements.db", "Providers, statement series, memberships, profiles, expectations, acquisition, and external candidates."),
                store("Paperless-ngx", "document authority", "Paperless documents and correspondent identity", "Supplies source documents, dates, titles, and metadata."),
            ],
        }),
        node({
            id: "correspondent-intelligence",
            label: "Correspondent Intelligence",
            lens: "feature",
            kind: "capability",
            parent: "document-operations",
            status: "partial",
            summary: "Profiles correspondents and curates document expectations, title policy, metadata, acquisition, and series.",
            details: "Substantial schema, Pydantic models, APIs, frontend review, and tests are implemented. The July roadmap still calls this future, so the canvas treats the capability as partial until review scale, expectation semantics, acquisition, and Tyrion reconciliation are complete.",
            paths: [
                "src/doc_intelligence_hub/modules/statements/correspondent_models.py",
                "src/doc_intelligence_hub/modules/statements/correspondent_service.py",
                "frontend/src/pages/CorrespondentReview.tsx",
                "docs/design/active/correspondent-intelligence-and-acquisition.md",
                "https://github.com/rsocko/owl/issues/90",
                "https://github.com/rsocko/owl/issues/91",
                "https://github.com/rsocko/owl/issues/92",
            ],
            tags: ["profile", "expectations", "roadmap-lag"],
            stores: [
                store("Paperless-ngx", "identity authority", "Correspondents and source document metadata", "Owns correspondent IDs and names."),
                store("OWL", "policy overlay", "/app/data/statements.db", "Profiles, aliases, expectations, sources, review state, and series bindings."),
            ],
        }),
        node({
            id: "eob-matching",
            label: "EOB & Bill Matching",
            lens: "feature",
            kind: "capability",
            parent: "document-operations",
            summary: "Extracts medical records and matches EOBs to provider bills with explainable confidence.",
            details: "The live pipeline classifies and extracts EOBs and bills, computes a configurable five-factor score, tracks payment lifecycle and billing errors, and supports rich review, alternatives, manual matching, history, and coverage analytics.",
            paths: [
                "src/doc_intelligence_hub/modules/eob_matching/",
                "src/doc_intelligence_hub/api/routers/eob.py",
                "frontend/src/pages/EobWorkspace.tsx",
                "docs/guide/eob-matching-guide.md",
            ],
            tags: ["medical", "matching", "payment"],
            stores: [
                store("OWL", "derived record authority", "/app/data/eob_matching.db", "Extracted EOBs, bills, matches, payments, runs, and match events."),
                store("Paperless-ngx", "document authority", "Paperless EOB and bill documents", "Owns original files and document metadata."),
            ],
        }),
        node({
            id: "human-judgment",
            label: "Human Judgment",
            lens: "feature",
            kind: "area",
            parent: "capabilities",
            summary: "Review, correction, relationship, and insight surfaces where OWL needs user judgment.",
            details: "Needs Review changes what OWL should believe; Action Queue tracks what the user should do. These are intentionally distinct workflows.",
            paths: ["docs/architecture/index.md", "docs/modules/triage-correction/design.md"],
            tags: ["human-in-the-loop"],
        }),
        node({
            id: "needs-review",
            label: "Needs Review",
            lens: "feature",
            kind: "capability",
            parent: "human-judgment",
            summary: "Routes uncertain matches, duplicates, groupings, orphans, and metadata to a correction workflow.",
            details: "The product name is Needs Review while code, APIs, and tables retain the triage name. Users can accept, reject, correct, match, split, merge, or defer. A resolution may create an Action, but does not always do so.",
            paths: [
                "src/doc_intelligence_hub/modules/triage/",
                "src/doc_intelligence_hub/api/routers/triage.py",
                "frontend/src/pages/TriageQueue.tsx",
                "docs/architecture/index.md",
            ],
            tags: ["triage", "correction", "review"],
            stores: [
                store("OWL", "system of record", "/app/data/triage.db", "Queue items, duplicates, relationships, corrections, and audit events."),
                store("Paperless-ngx", "write-back target", "Document metadata", "Receives confirmed metadata corrections where configured."),
            ],
        }),
        node({
            id: "document-relationships",
            label: "Document Relationships",
            lens: "feature",
            kind: "capability",
            parent: "human-judgment",
            summary: "Projects typed links between documents and uses them to improve priority and context.",
            details: "OWL models follows, supersedes, supports, and same-sequence relationships with source, confidence, active state, and priority adjustment. Detection and consolidation on ingestion remain planned extensions.",
            paths: [
                "src/doc_intelligence_hub/modules/triage/relationships.py",
                "src/doc_intelligence_hub/modules/triage/relationship_projection.py",
                "docs/design/active/document-relationships.md",
                "https://github.com/rsocko/owl/issues/64",
                "https://github.com/rsocko/owl/issues/65",
            ],
            tags: ["graph", "notices", "sequence"],
            stores: [
                store("OWL", "relationship authority", "/app/data/triage.db: document_relationships", "Typed document edges and their provenance."),
                store("Paperless-ngx", "node authority", "Paperless document IDs", "Owns the documents at both ends of each relationship."),
            ],
        }),
        node({
            id: "alerts-insights",
            label: "Alerts & Insights",
            lens: "feature",
            kind: "capability",
            parent: "human-judgment",
            summary: "Evaluates rules, emits cross-module alerts, and explains trends and exceptions.",
            details: "A three-tier rule engine combines YAML definitions, database configuration, and runtime APIs. APScheduler runs evaluation; alert CRUD, acknowledge/resolve, charts, sparklines, and EOB emission are implemented.",
            paths: [
                "src/doc_intelligence_hub/core/alerts.py",
                "src/doc_intelligence_hub/modules/analysis/",
                "frontend/src/pages/Insights.tsx",
                "config/analysis-rules.yaml",
            ],
            tags: ["rules", "analytics", "alerts"],
            stores: [
                store("OWL", "alert authority", "/app/data/alerts.db", "Current alert lifecycle."),
                store("OWL", "rule and insight state", "Analysis database and config/analysis-rules.yaml", "Configured rules and generated insight state."),
            ],
        }),
        node({
            id: "document-views",
            label: "Document Views",
            lens: "feature",
            kind: "capability",
            parent: "human-judgment",
            summary: "Defines safe, operator-curated launches into Paperless saved views and OWL review routes.",
            details: "Views are allowlisted configuration, not arbitrary persisted queries. They can target Paperless saved views or OWL-native triage, EOB, grouping, and orphan routes.",
            paths: [
                "src/doc_intelligence_hub/core/document_views.py",
                "src/doc_intelligence_hub/api/routers/document_views.py",
                "frontend/src/pages/DocumentViews.tsx",
                "config/document-views.example.yaml",
            ],
            tags: ["navigation", "saved-view"],
            stores: [
                store("OWL", "configuration authority", "Document views YAML configuration", "Defines labels, destinations, and allowlisted route targets."),
                store("Paperless-ngx", "optional destination", "Saved views", "Owns Paperless query definitions when the destination is external."),
            ],
        }),
        node({
            id: "ecosystem",
            label: "Ecosystem Integration",
            lens: "feature",
            kind: "area",
            parent: "capabilities",
            summary: "Connects OWL to document, work, finance, and AI systems without transferring domain authority.",
            details: "Paperless remains document authority, OWL remains document-intelligence authority, Mission Control projects daily work, and Tyrion remains finance interpretation authority.",
            paths: ["docs/architecture/index.md", "docs/guide/mission-control-integration.md"],
            tags: ["integration", "ownership"],
        }),
        node({
            id: "paperless-integration",
            label: "Paperless Integration",
            lens: "feature",
            kind: "capability",
            parent: "ecosystem",
            summary: "Reads source documents and metadata and writes bounded tags, fields, and corrections.",
            details: "The shared async client supports pagination and document, tag, correspondent, custom-field, and metadata operations. Paperless owns original documents; OWL stores derived intelligence and never replaces document identity.",
            paths: [
                "src/doc_intelligence_hub/core/paperless/client.py",
                "src/doc_intelligence_hub/core/paperless/metadata.py",
                "docs/design/active/paperless-metadata-and-document-summary.md",
            ],
            tags: ["source-of-truth", "metadata"],
        }),
        node({
            id: "mission-control-integration",
            label: "Mission Control",
            lens: "feature",
            kind: "capability",
            parent: "ecosystem",
            summary: "Projects OWL actions, missing statements, and unmatched medical records into the daily work surface.",
            details: "Mission Control polls dedicated connector endpoints and reconciles bounded action state. OWL remains the source authority and applies Paperless-aware completion, dismissal, reopen, snooze, and feedback semantics.",
            paths: [
                "src/doc_intelligence_hub/api/routers/mc_connector.py",
                "docs/guide/mission-control-integration.md",
            ],
            tags: ["connector", "projection", "tasks"],
        }),
        node({
            id: "tyrion-signals",
            label: "Tyrion Signals",
            lens: "feature",
            kind: "capability",
            parent: "ecosystem",
            status: "partial",
            summary: "Accepts bounded finance-derived candidates for document expectations without active document-to-transaction reconciliation.",
            details: "OWL has external signal source, generation, connection, and candidate schemas plus APIs. No production OWL-to-Tyrion evidence transport or authoritative reconciliation loop is active. Mission Control may relay facts but does not own their meaning.",
            paths: [
                "src/doc_intelligence_hub/modules/statements/external_signals.py",
                "src/doc_intelligence_hub/modules/statements/database.py",
                "docs/design/active/correspondent-intelligence-and-acquisition.md",
            ],
            tags: ["finance", "candidate", "bounded-contract"],
            stores: [
                store("Tyrion", "finance interpretation authority", "Tyrion finance stores", "Produces bounded recurring/account candidates; does not own OWL expectations."),
                store("Mission Control", "optional transport", "Connector relay", "May mediate transport without becoming evidence authority."),
                store("OWL", "candidate and decision authority", "/app/data/statements.db: external_signal_* and external_document_candidates", "Persists imported candidate generations and OWL review state."),
            ],
        }),
        node({
            id: "bifrost-integration",
            label: "Bifrost AI Gateway",
            lens: "feature",
            kind: "capability",
            parent: "ecosystem",
            summary: "Routes OpenAI-compatible classification and extraction requests to configured local or cloud models.",
            details: "Bifrost centralizes model routing, fallback, rate limiting, and usage. Deterministic or rule-based fallbacks remain available for selected pipelines.",
            paths: ["src/doc_intelligence_hub/core/llm.py", "docs/architecture/index.md"],
            tags: ["llm", "ollama", "gateway"],
        }),
        node({
            id: "planned-delivery",
            label: "Planned Delivery",
            lens: "feature",
            kind: "area",
            parent: "capabilities",
            status: "planned",
            summary: "Open work and implementation-ready designs that are not current behavior.",
            details: "These nodes should not be interpreted as available household scenarios. Each is tied to current issues or design artifacts.",
            paths: ["docs/feature-roadmap.md", "docs/design/active/go-forward-plan.md"],
            tags: ["future"],
        }),
        node({
            id: "acquisition",
            label: "Document Acquisition",
            lens: "feature",
            kind: "capability",
            parent: "planned-delivery",
            status: "planned",
            summary: "Acquire expected documents through idempotent email, API, portal, or mail workflows.",
            details: "The data model includes acquisition sources, but connector health, lifecycle, and production email/API acquisition are open work.",
            paths: [
                "docs/design/active/correspondent-intelligence-and-acquisition.md",
                "https://github.com/rsocko/owl/issues/74",
                "https://github.com/rsocko/owl/issues/75",
            ],
            tags: ["email", "api", "connector"],
        }),
        node({
            id: "event-ingestion",
            label: "Event-driven Ingestion",
            lens: "feature",
            kind: "capability",
            parent: "planned-delivery",
            status: "planned",
            summary: "Trigger bounded OWL enrichment and analysis when Paperless creates or updates a document.",
            details: "Webhook foundations exist, but durable publication, fast-processing rules, and a complete ingestion contract remain open.",
            paths: [
                "src/doc_intelligence_hub/core/webhooks.py",
                "src/doc_intelligence_hub/api/routers/webhooks.py",
                "https://github.com/rsocko/owl/issues/28",
                "https://github.com/rsocko/owl/issues/67",
                "https://github.com/rsocko/owl/issues/81",
            ],
            tags: ["webhook", "events", "durability"],
        }),
        node({
            id: "ocr-quality",
            label: "OCR Quality Workflow",
            lens: "feature",
            kind: "capability",
            parent: "planned-delivery",
            status: "planned",
            summary: "Assess corpus OCR, compare safe candidates, and explicitly apply Paperless document versions.",
            details: "This is design-only with zero implementation. The plan begins with read-only inventory and calibration, then candidate comparison, version application with rollback, and downstream re-analysis. Automatic initial replacement is out of scope.",
            paths: [
                "docs/design/proposed/ocr-quality-implementation-plan.md",
                "docs/modules/ocr-quality/",
                "https://github.com/rsocko/owl/issues/25",
                "https://github.com/rsocko/owl/issues/29",
                "https://github.com/rsocko/owl/issues/115",
            ],
            tags: ["design-only", "paperless-version", "review-first"],
        }),
        node({
            id: "general-reconciliation",
            label: "General Reconciliation",
            lens: "feature",
            kind: "capability",
            parent: "planned-delivery",
            status: "proposed",
            summary: "Generalize EOB matching into recipe-driven receipt, bill, order, insurance, contract, and statement reconciliation.",
            details: "The design extracts generic recipes, scoring, lifecycle, review, and API contracts from EOB matching. No reconciliation module exists in source today.",
            paths: [
                "docs/modules/reconciliation/design.md",
                "docs/modules/reconciliation/ui-flows.md",
                "docs/feature-roadmap.md",
            ],
            tags: ["design-only", "matching", "recipes"],
        }),
        node({
            id: "financial-reconciliation",
            label: "OWL ↔ Tyrion Reconciliation",
            lens: "feature",
            kind: "capability",
            parent: "planned-delivery",
            status: "proposed",
            summary: "Match bills, receipts, EOBs, and statements with authoritative Monarch transactions.",
            details: "The intended future loop preserves links to the OWL document and Monarch transaction, detects missing or duplicate payments and amount variance, and supports confirm, reject, rematch, defer, and reopen. There is no active production transport or reconciliation contract today.",
            paths: [
                "docs/feature-roadmap.md",
                "docs/design/active/correspondent-intelligence-and-acquisition.md",
                "https://github.com/rsocko/owl/issues/27",
            ],
            tags: ["tyrion", "monarch", "future"],
            stores: [
                store("Paperless-ngx", "document authority", "Documents and metadata", "Owns bill, receipt, statement, and EOB files."),
                store("OWL", "document interpretation authority", "OWL module databases", "Owns extractions, relationships, candidate matches, and review decisions."),
                store("Tyrion", "finance interpretation authority", "Tyrion finance stores", "Owns bounded finance conclusions and policy."),
                store("Monarch", "financial record authority", "Monarch", "Owns transactions, accounts, categories, and recurring obligations."),
                store("Mission Control", "experience and coordination", "Finance and document projections", "Would render exceptions and route attention without taking source authority."),
            ],
        }),
        node({
            id: "active-learning",
            label: "Feedback & Active Learning",
            lens: "feature",
            kind: "capability",
            parent: "planned-delivery",
            status: "planned",
            summary: "Use confirmed and rejected reviews to improve classification and ranking.",
            details: "Feedback persistence and connector endpoints exist for the Action Queue, but closed-loop model improvement is not implemented.",
            paths: [
                "src/doc_intelligence_hub/modules/action_queue/database.py",
                "https://github.com/rsocko/owl/issues/13",
            ],
            tags: ["feedback", "ml"],
        }),
        node({
            id: "experience-hardening",
            label: "Experience & Security",
            lens: "feature",
            kind: "capability",
            parent: "planned-delivery",
            status: "planned",
            summary: "Add onboarding, responsive review, discoverable shortcuts, authentication, and managed AI credentials.",
            details: "OWL is currently an internal trusted-network service. Public exposure would require authentication and authorization. Onboarding and responsive review remain planned UX work.",
            paths: [
                "docs/architecture/index.md",
                "https://github.com/rsocko/owl/issues/9",
                "https://github.com/rsocko/owl/issues/11",
                "https://github.com/rsocko/owl/issues/12",
                "https://github.com/rsocko/owl/issues/19",
                "https://github.com/rsocko/owl/issues/22",
            ],
            tags: ["auth", "responsive", "onboarding"],
        }),

        node({
            id: "architecture",
            label: "OWL Architecture",
            lens: "architecture",
            kind: "root",
            summary: "A single-container FastAPI and React application with modular domain services and isolated SQLite stores.",
            details: "Paperless is the document source of truth. OWL modules independently query it through a shared client, persist derived domain state, and surface actions and alerts through OWL and Mission Control.",
            paths: ["docs/architecture/index.md", "Dockerfile", "docker-compose.yml"],
            tags: ["system"],
        }),
        node({
            id: "external-systems",
            label: "External Systems",
            lens: "architecture",
            kind: "layer",
            parent: "architecture",
            summary: "Systems that supply documents, models, finance facts, or daily user surfaces.",
            details: "Each boundary retains a distinct authority: Paperless for documents, Monarch for financial records, Tyrion for finance interpretation, OWL for document intelligence, and Mission Control for daily experience.",
            paths: ["docs/architecture/index.md"],
            tags: ["boundaries"],
        }),
        node({
            id: "paperless-system",
            label: "Paperless-ngx",
            lens: "architecture",
            kind: "external",
            parent: "external-systems",
            summary: "Document, correspondent, tag, type, custom-field, and saved-view authority.",
            details: "OWL reads source documents and writes bounded metadata. Original document identity and files remain in Paperless.",
            paths: ["src/doc_intelligence_hub/core/paperless/client.py"],
            tags: ["document-system-of-record"],
            system: "Paperless-ngx",
        }),
        node({
            id: "mission-control-system",
            label: "Mission Control",
            lens: "architecture",
            kind: "external",
            parent: "external-systems",
            summary: "Daily experience, action projection, attention routing, and optional integration transport.",
            details: "Mission Control consumes connector contracts and reconciles status; it does not become the authority for OWL document interpretation or Tyrion finance interpretation.",
            paths: ["docs/guide/mission-control-integration.md"],
            tags: ["experience"],
            system: "Mission Control",
        }),
        node({
            id: "tyrion-system",
            label: "Tyrion",
            lens: "architecture",
            kind: "external",
            parent: "external-systems",
            status: "partial",
            summary: "Bounded household-finance interpretation and policy service.",
            details: "OWL can persist Tyrion-derived document candidates, but no active end-to-end reconciliation transport is deployed.",
            paths: ["docs/design/active/correspondent-intelligence-and-acquisition.md"],
            tags: ["finance"],
            system: "Tyrion",
        }),
        node({
            id: "bifrost-system",
            label: "Bifrost",
            lens: "architecture",
            kind: "external",
            parent: "external-systems",
            summary: "OpenAI-compatible gateway for local and cloud model routing.",
            details: "Modules use the shared LLM abstraction rather than provider-specific calls.",
            paths: ["src/doc_intelligence_hub/core/llm.py"],
            tags: ["ai"],
            system: "Bifrost",
        }),
        node({
            id: "delivery-layer",
            label: "Delivery Layer",
            lens: "architecture",
            kind: "layer",
            parent: "architecture",
            summary: "FastAPI routers and React views expose one set of domain contracts.",
            details: "The React/Vite SPA is served by FastAPI. External clients use the same routers, with dedicated Mission Control compatibility endpoints.",
            paths: ["src/doc_intelligence_hub/api/", "frontend/src/"],
            tags: ["api", "ui"],
        }),
        node({
            id: "fastapi-app",
            label: "FastAPI App",
            lens: "architecture",
            kind: "component",
            parent: "delivery-layer",
            summary: "App factory, lifecycle, router mounting, static frontend, and shared dependencies.",
            details: "Startup loads settings, initializes Paperless and scheduling, mounts module routers, and serves the compiled SPA.",
            paths: ["src/doc_intelligence_hub/api/app.py"],
            tags: ["python", "http"],
        }),
        node({
            id: "react-spa",
            label: "React Admin SPA",
            lens: "architecture",
            kind: "component",
            parent: "delivery-layer",
            summary: "Primary direct OWL interface for operations, review, configuration, and analysis.",
            details: "The Vite/TypeScript HashRouter application consumes OWL APIs and is compiled into the single deployment image.",
            paths: ["frontend/src/App.tsx", "frontend/src/pages/"],
            tags: ["react", "vite"],
        }),
        node({
            id: "mc-connector",
            label: "MC Connector",
            lens: "architecture",
            kind: "component",
            parent: "delivery-layer",
            summary: "Compatibility contract for Mission Control action and alert projections.",
            details: "Exposes bounded arrays and lifecycle operations for actions, missing statements, and unmatched EOB records.",
            paths: ["src/doc_intelligence_hub/api/routers/mc_connector.py"],
            tags: ["integration-api"],
        }),
        node({
            id: "domain-layer",
            label: "Domain Modules",
            lens: "architecture",
            kind: "layer",
            parent: "architecture",
            summary: "Independent modules own their logic, models, routers, and persistence.",
            details: "Modules do not read each other's databases. Cross-module alerting flows through the shared Alerts API rather than shared mutable storage.",
            paths: ["src/doc_intelligence_hub/modules/"],
            tags: ["modular"],
        }),
        node({
            id: "aq-module",
            label: "Action Queue Module",
            lens: "architecture",
            kind: "component",
            parent: "domain-layer",
            summary: "Document-to-action classification, enrichment, risk, and lifecycle.",
            details: "Owns analysis, fast path, fallback, pipeline, enrichment, risk scoring, and action persistence.",
            paths: ["src/doc_intelligence_hub/modules/action_queue/"],
            tags: ["action"],
        }),
        node({
            id: "statements-module",
            label: "Statements Module",
            lens: "architecture",
            kind: "component",
            parent: "domain-layer",
            summary: "Series discovery, correspondent intelligence, expectations, acquisition, and external candidates.",
            details: "The broadest module combines recurring-document detection with curated correspondent policy and partially implemented external signal ingestion.",
            paths: ["src/doc_intelligence_hub/modules/statements/"],
            tags: ["statements", "correspondents"],
        }),
        node({
            id: "eob-module",
            label: "EOB Module",
            lens: "architecture",
            kind: "component",
            parent: "domain-layer",
            summary: "Medical classification, extraction, weighted matching, billing errors, and payment lifecycle.",
            details: "Owns EOB and bill derived records and their match decisions.",
            paths: ["src/doc_intelligence_hub/modules/eob_matching/"],
            tags: ["medical"],
        }),
        node({
            id: "triage-module",
            label: "Triage Module",
            lens: "architecture",
            kind: "component",
            parent: "domain-layer",
            summary: "Needs Review queue, duplicates, relationships, correction projection, and audit.",
            details: "Retains triage as its code-level name while the product surface uses Needs Review.",
            paths: ["src/doc_intelligence_hub/modules/triage/"],
            tags: ["review"],
        }),
        node({
            id: "analysis-module",
            label: "Analysis Module",
            lens: "architecture",
            kind: "component",
            parent: "domain-layer",
            summary: "Rule registry, execution, context construction, and insight routing.",
            details: "Combines deterministic, LLM, Action Queue, and n8n-oriented rule types behind one execution model.",
            paths: ["src/doc_intelligence_hub/modules/analysis/"],
            tags: ["rules"],
        }),
        node({
            id: "shared-core",
            label: "Shared Core",
            lens: "architecture",
            kind: "layer",
            parent: "architecture",
            summary: "Configuration, Paperless access, LLM access, alerts, scheduling, resilience, and webhooks.",
            details: "Shared infrastructure is intentionally narrow; domain data remains isolated in module stores.",
            paths: ["src/doc_intelligence_hub/core/"],
            tags: ["shared"],
        }),
        node({
            id: "paperless-client",
            label: "Paperless Client",
            lens: "architecture",
            kind: "component",
            parent: "shared-core",
            summary: "Async boundary for document and metadata operations.",
            details: "Centralizes token authentication, pagination, retries, and API translation.",
            paths: ["src/doc_intelligence_hub/core/paperless/client.py"],
            tags: ["http-client"],
        }),
        node({
            id: "alerts-engine",
            label: "Alerts Engine",
            lens: "architecture",
            kind: "component",
            parent: "shared-core",
            summary: "Shared cross-module notification and lifecycle API.",
            details: "The documented module boundary uses alert APIs rather than direct database reads.",
            paths: ["src/doc_intelligence_hub/core/alerts.py"],
            tags: ["cross-module"],
        }),
        node({
            id: "scheduler",
            label: "Scheduler",
            lens: "architecture",
            kind: "component",
            parent: "shared-core",
            summary: "APScheduler and container schedules coordinate recurring analysis.",
            details: "Supports runtime schedule configuration in addition to job-profile and cron deployment patterns.",
            paths: ["src/doc_intelligence_hub/core/scheduler.py", "config/schedules.yaml"],
            tags: ["automation"],
        }),
        node({
            id: "storage-layer",
            label: "Isolated Storage",
            lens: "architecture",
            kind: "layer",
            parent: "architecture",
            summary: "SQLite databases isolate module state under the persistent data volume.",
            details: "Action Queue, Statements, EOB Matching, Triage, Alerts, and Analysis own separate schemas. This avoids shared mutable state but requires APIs for cross-domain behavior.",
            paths: [
                "src/doc_intelligence_hub/modules/action_queue/database.py",
                "src/doc_intelligence_hub/modules/statements/database.py",
                "src/doc_intelligence_hub/modules/eob_matching/database.py",
                "src/doc_intelligence_hub/modules/triage/database.py",
            ],
            tags: ["sqlite", "sqlalchemy"],
        }),
        node({
            id: "deployment",
            label: "Deployment",
            lens: "architecture",
            kind: "layer",
            parent: "architecture",
            summary: "Single Docker image behind Traefik with persistent SQLite storage.",
            details: "FastAPI serves the UI and APIs on port 8001. The deployment is intended for an internal trusted homelab network.",
            paths: ["Dockerfile", "docker-compose.yml", ".github/workflows/publish-container.yml"],
            tags: ["docker", "homelab"],
        }),

        node({
            id: "entity-model",
            label: "OWL Domain Model",
            lens: "entity",
            kind: "root",
            summary: "Logical entities that OWL defines, derives, reviews, or projects.",
            details: "Select an entity to see its definition, exact source paths, physical storage, and cross-system ownership. Entity identity and derived intelligence may intentionally live in different systems.",
            paths: ["src/doc_intelligence_hub/modules/"],
            tags: ["entities"],
        }),
        node({
            id: "document-entities",
            label: "Document & Metadata",
            lens: "entity",
            kind: "area",
            parent: "entity-model",
            summary: "Paperless-owned documents with OWL-owned derived metadata and navigation.",
            details: "OWL refers to documents by Paperless identity and stores domain-specific projections rather than copying the original files.",
            paths: ["src/doc_intelligence_hub/core/paperless/"],
            tags: ["paperless"],
        }),
        node({
            id: "document-entity",
            label: "Document",
            lens: "entity",
            kind: "entity",
            parent: "document-entities",
            summary: "A Paperless document with identity, title, dates, correspondent, type, tags, and source file.",
            details: "OWL's DocumentRecord and module-specific records mirror or derive from the Paperless document. The original document and canonical document ID remain in Paperless.",
            paths: [
                "src/doc_intelligence_hub/modules/statements/models.py",
                "src/doc_intelligence_hub/core/paperless/client.py",
            ],
            tags: ["source"],
            system: "Paperless-ngx",
            stores: [
                store("Paperless-ngx", "system of record", "Paperless document database and media storage", "Canonical ID, file, title, dates, correspondent, document type, tags, and custom fields."),
                store("OWL", "derived projections", "Module-specific SQLite records", "Stores extraction, classification, grouping, match, action, and review state keyed by Paperless document ID."),
            ],
        }),
        node({
            id: "metadata-entity",
            label: "Document Metadata",
            lens: "entity",
            kind: "entity",
            parent: "document-entities",
            summary: "Tags, correspondent, document type, custom fields, and migration-safe snapshots and patches.",
            details: "Paperless owns current metadata values. OWL defines canonical expectations, reads and writes bounded changes, and records protected migration state where required.",
            paths: [
                "src/doc_intelligence_hub/core/paperless/metadata.py",
                "src/doc_intelligence_hub/modules/metadata_migration/models.py",
                "docs/design/active/paperless-metadata-and-document-summary.md",
            ],
            tags: ["custom-fields", "account-identifier"],
            system: "Paperless-ngx",
            stores: [
                store("Paperless-ngx", "system of record", "Tags, correspondents, document types, and custom fields", "Current metadata attached to each document."),
                store("OWL", "policy and migration audit", "Metadata migration state and statements.db policy", "Expected values, snapshots, patches, protected records, and correction history."),
            ],
        }),
        node({
            id: "document-view-entity",
            label: "Document View",
            lens: "entity",
            kind: "entity",
            parent: "document-entities",
            summary: "A named, allowlisted launch into a Paperless saved view or OWL-native review route.",
            details: "This is a configuration entity rather than a database row. It stores safe destinations, not arbitrary user query text.",
            paths: ["src/doc_intelligence_hub/core/document_views.py", "config/document-views.example.yaml"],
            tags: ["configuration"],
            stores: [
                store("OWL", "definition authority", "Document views YAML", "Name, label, destination kind, and route or saved-view target."),
                store("Paperless-ngx", "optional query authority", "Paperless saved view", "Owns the saved query when the view launches externally."),
            ],
        }),
        node({
            id: "statement-entities",
            label: "Statements & Correspondents",
            lens: "entity",
            kind: "area",
            parent: "entity-model",
            status: "partial",
            summary: "Recurring document groupings and the policy used to expect and acquire them.",
            details: "Core statement tracking is active. The broader correspondent and external-signal model is substantial but still being completed.",
            paths: ["src/doc_intelligence_hub/modules/statements/"],
            tags: ["recurrence"],
        }),
        node({
            id: "correspondent-entity",
            label: "Correspondent",
            lens: "entity",
            kind: "entity",
            parent: "statement-entities",
            summary: "The sender, issuer, or organization associated with a document.",
            details: "Paperless owns correspondent identity and display name. OWL references that identity and overlays a curated Correspondent Profile.",
            paths: [
                "src/doc_intelligence_hub/modules/statements/correspondent_models.py",
                "src/doc_intelligence_hub/modules/statements/database.py",
            ],
            tags: ["issuer"],
            system: "Paperless-ngx",
            stores: [
                store("Paperless-ngx", "identity authority", "Paperless correspondents", "Canonical correspondent ID and name."),
                store("OWL", "reference and overlay", "/app/data/statements.db", "References the Paperless ID from profiles, series, expectations, aliases, and acquisition sources."),
            ],
        }),
        node({
            id: "correspondent-profile-entity",
            label: "Correspondent Profile",
            lens: "entity",
            kind: "entity",
            parent: "statement-entities",
            status: "partial",
            summary: "OWL's reviewed policy overlay for one Paperless correspondent.",
            details: "Captures review and lifecycle state, aliases, defaults, classification, title and metadata expectations, and related operational policy.",
            paths: [
                "src/doc_intelligence_hub/modules/statements/correspondent_models.py",
                "src/doc_intelligence_hub/modules/statements/database.py",
                "frontend/src/pages/CorrespondentReview.tsx",
            ],
            tags: ["overlay", "review"],
            stores: [
                store("OWL", "system of record", "/app/data/statements.db: correspondent_profiles and aliases", "OWL-specific reviewed policy keyed to a Paperless correspondent."),
                store("Paperless-ngx", "identity dependency", "Paperless correspondents", "Provides the correspondent ID and name the profile augments."),
            ],
        }),
        node({
            id: "statement-series-entity",
            label: "Statement Series",
            lens: "entity",
            kind: "entity",
            parent: "statement-entities",
            summary: "A curated or detected recurring sequence of related statement documents.",
            details: "Stores correspondent, frequency, account identifier, expected amount/currency, review state, and manual-curation state. Membership is many-to-many through series_documents.",
            paths: [
                "src/doc_intelligence_hub/modules/statements/models.py",
                "src/doc_intelligence_hub/modules/statements/database.py",
            ],
            tags: ["series", "cadence"],
            stores: [
                store("OWL", "system of record", "/app/data/statements.db: statement_series and series_documents", "Series policy and membership."),
                store("Paperless-ngx", "member identity authority", "Paperless documents", "Owns every member document referenced by the join table."),
            ],
        }),
        node({
            id: "expectation-entity",
            label: "Document Expectation",
            lens: "entity",
            kind: "entity",
            parent: "statement-entities",
            status: "partial",
            summary: "Confirmed policy describing what document should arrive, when, and with which title and metadata.",
            details: "Belongs to a correspondent profile and can bind to a statement series. It can be proposed by external candidates but only OWL review promotes it into active policy.",
            paths: [
                "src/doc_intelligence_hub/modules/statements/correspondent_models.py",
                "src/doc_intelligence_hub/modules/statements/database.py",
            ],
            tags: ["policy", "expected-document"],
            stores: [
                store("OWL", "system of record", "/app/data/statements.db: document_expectations", "Cadence, kind, title, metadata, importance, calendar, source, and review state."),
                store("Tyrion", "candidate source only", "External signals", "May suggest account or recurring candidates but does not own the OWL expectation."),
            ],
        }),
        node({
            id: "acquisition-source-entity",
            label: "Acquisition Source",
            lens: "entity",
            kind: "entity",
            parent: "statement-entities",
            status: "partial",
            summary: "Describes how documents for a correspondent are obtained.",
            details: "Represents mail, email/API connector, portal, or another source plus lifecycle and health. The schema exists; complete connector execution and health remain planned.",
            paths: [
                "src/doc_intelligence_hub/modules/statements/database.py",
                "docs/design/active/correspondent-intelligence-and-acquisition.md",
            ],
            tags: ["connector", "source"],
            stores: [
                store("OWL", "system of record", "/app/data/statements.db: acquisition_sources", "Source kind, configuration reference, state, and health-related policy."),
                store("External provider", "delivery authority", "Email, API, portal, or physical mail", "Owns delivery before a document reaches Paperless."),
            ],
        }),
        node({
            id: "external-candidate-entity",
            label: "External Document Candidate",
            lens: "entity",
            kind: "entity",
            parent: "statement-entities",
            status: "partial",
            summary: "A generation-scoped external signal proposing a possible OWL document expectation.",
            details: "The candidate can originate from Tyrion finance signals directly or through Mission Control transport. It is not itself an active expectation and requires OWL-side review or promotion.",
            paths: [
                "src/doc_intelligence_hub/modules/statements/external_signals.py",
                "src/doc_intelligence_hub/modules/statements/database.py",
            ],
            tags: ["tyrion", "proposal", "generation"],
            stores: [
                store("OWL", "candidate authority after import", "/app/data/statements.db: external_signal_* and external_document_candidates", "Connection, source, generation, candidate payload, and review state."),
                store("Tyrion", "origin authority", "Tyrion recurring/account evidence", "Produces bounded finance evidence without deciding OWL policy."),
                store("Mission Control", "optional transport", "Connector relay", "Can relay the contract but does not reinterpret it."),
            ],
        }),
        node({
            id: "medical-entities",
            label: "Medical Matching",
            lens: "entity",
            kind: "area",
            parent: "entity-model",
            summary: "Derived EOB and bill records connected by scored, reviewable matches.",
            details: "Paperless owns the original medical documents; OWL owns extraction, match, payment, and review records.",
            paths: ["src/doc_intelligence_hub/modules/eob_matching/"],
            tags: ["eob", "bill"],
        }),
        node({
            id: "eob-entity",
            label: "EOB",
            lens: "entity",
            kind: "entity",
            parent: "medical-entities",
            summary: "An extracted Explanation of Benefits record.",
            details: "Includes insurer, patient, claim, dates of service, charged/allowed/paid/patient amounts, procedures, and extraction provenance.",
            paths: [
                "src/doc_intelligence_hub/modules/eob_matching/models.py",
                "src/doc_intelligence_hub/modules/eob_matching/database.py",
            ],
            tags: ["insurance", "extraction"],
            stores: [
                store("Paperless-ngx", "document authority", "Paperless EOB document", "Owns the source file and canonical document ID."),
                store("OWL", "extraction authority", "/app/data/eob_matching.db: eob_records", "Stores structured medical facts derived from the document."),
            ],
        }),
        node({
            id: "bill-entity",
            label: "Bill",
            lens: "entity",
            kind: "entity",
            parent: "medical-entities",
            summary: "An extracted provider bill record.",
            details: "Includes provider, invoice, dates of service, due date, amount, balance, payment status, procedures, and extraction provenance.",
            paths: [
                "src/doc_intelligence_hub/modules/eob_matching/models.py",
                "src/doc_intelligence_hub/modules/eob_matching/database.py",
            ],
            tags: ["provider", "invoice"],
            stores: [
                store("Paperless-ngx", "document authority", "Paperless bill document", "Owns the source file and canonical document ID."),
                store("OWL", "extraction authority", "/app/data/eob_matching.db: bill_records", "Stores structured bill facts derived from the document."),
                store("Monarch", "future payment authority", "Monarch transactions", "Would own authoritative payment records in a future reconciliation flow."),
            ],
        }),
        node({
            id: "match-entity",
            label: "EOB ↔ Bill Match",
            lens: "entity",
            kind: "entity",
            parent: "medical-entities",
            summary: "A scored association between one EOB and one provider bill.",
            details: "Stores confidence and factor breakdown across date, provider, patient, amount, and procedures, plus review status, payment lifecycle, notes, and billing-error classification.",
            paths: [
                "src/doc_intelligence_hub/modules/eob_matching/matcher.py",
                "src/doc_intelligence_hub/modules/eob_matching/models.py",
                "src/doc_intelligence_hub/modules/eob_matching/database.py",
            ],
            tags: ["confidence", "review"],
            stores: [
                store("OWL", "system of record", "/app/data/eob_matching.db: matches", "Scoring, decision, lifecycle, notes, and error state."),
                store("Paperless-ngx", "endpoint identity", "EOB and bill documents", "Owns the two source documents."),
            ],
        }),
        node({
            id: "payment-entity",
            label: "Payment Record",
            lens: "entity",
            kind: "entity",
            parent: "medical-entities",
            summary: "OWL's payment-lifecycle observation attached to a medical match.",
            details: "Tracks unpaid, partial, paid, and overpaid state and related amounts. It is derived operational state, not an authoritative bank transaction.",
            paths: ["src/doc_intelligence_hub/modules/eob_matching/database.py"],
            tags: ["lifecycle"],
            stores: [
                store("OWL", "derived lifecycle authority", "/app/data/eob_matching.db: payments", "Payment observations tied to a match."),
                store("Monarch", "future financial authority", "Monarch transactions", "Would own bank-side payment truth if reconciliation is implemented."),
            ],
        }),
        node({
            id: "match-event-entity",
            label: "Match Event",
            lens: "entity",
            kind: "entity",
            parent: "medical-entities",
            summary: "Audit event recording a match lifecycle or review change.",
            details: "Preserves match history for explainability and UI timelines.",
            paths: ["src/doc_intelligence_hub/modules/eob_matching/database.py"],
            tags: ["audit"],
            stores: [
                store("OWL", "system of record", "/app/data/eob_matching.db: match_events", "Append-oriented match audit history."),
            ],
        }),
        node({
            id: "work-entities",
            label: "Work & Attention",
            lens: "entity",
            kind: "area",
            parent: "entity-model",
            summary: "Actionable work, informational alerts, and derived insights.",
            details: "Actions represent things a user should do; alerts and insights explain changes or exceptions. Mission Control can project these without owning them.",
            paths: ["src/doc_intelligence_hub/modules/action_queue/", "src/doc_intelligence_hub/core/alerts.py"],
            tags: ["attention"],
        }),
        node({
            id: "action-entity",
            label: "Action",
            lens: "entity",
            kind: "entity",
            parent: "work-entities",
            summary: "A recommended next step caused by a document.",
            details: "Carries type, title, description, lifecycle status, urgency, severity, due date, risk and reasoning, source document identity, Paperless write-back state, and Mission Control sync metadata.",
            paths: [
                "src/doc_intelligence_hub/modules/action_queue/database.py",
                "src/doc_intelligence_hub/modules/action_queue/lifecycle.py",
            ],
            tags: ["task", "lifecycle"],
            stores: [
                store("OWL", "system of record", "/app/data/action_queue.db: actions", "Canonical classifier output and lifecycle."),
                store("Paperless-ngx", "source and write-back target", "Document tags and custom fields", "Owns the source document and receives bounded status metadata."),
                store("Mission Control", "projection", "Document Intelligence task projection", "Surfaces daily work and sends reconciled lifecycle mutations back to OWL."),
            ],
        }),
        node({
            id: "action-feedback-entity",
            label: "Action Feedback",
            lens: "entity",
            kind: "entity",
            parent: "work-entities",
            summary: "A user confirmation, rejection, or correction of classifier output.",
            details: "Feedback is persisted and exposed through connector APIs, but automated closed-loop model improvement remains planned.",
            paths: ["src/doc_intelligence_hub/modules/action_queue/database.py"],
            tags: ["learning", "correction"],
            stores: [
                store("OWL", "system of record", "/app/data/action_queue.db: action_feedback", "Original classification, user response, correction, and context."),
            ],
        }),
        node({
            id: "alert-entity",
            label: "Alert",
            lens: "entity",
            kind: "entity",
            parent: "work-entities",
            summary: "A unified cross-module notification with severity and lifecycle.",
            details: "Includes module, alert type, title, message, severity, action URL, acknowledge/resolve state, and source reference.",
            paths: ["src/doc_intelligence_hub/core/alerts.py"],
            tags: ["notification"],
            stores: [
                store("OWL", "system of record", "/app/data/alerts.db: alerts", "Canonical alert lifecycle."),
                store("Mission Control", "optional projection", "Notification projection", "May surface attention while OWL retains the alert record."),
            ],
        }),
        node({
            id: "insight-entity",
            label: "Insight",
            lens: "entity",
            kind: "entity",
            parent: "work-entities",
            summary: "A rule-engine result describing a comparison, anomaly, trend, or compliance finding.",
            details: "Insights may be informational or routed into alerts depending on the rule and confidence.",
            paths: [
                "src/doc_intelligence_hub/modules/analysis/models.py",
                "src/doc_intelligence_hub/modules/analysis/insight_router.py",
            ],
            tags: ["analytics"],
            stores: [
                store("OWL", "derived state", "Analysis database", "Insight response, provenance, confidence, and routing state."),
                store("OWL", "rule definition", "config/analysis-rules.yaml and rule database", "Defines evaluation and routing policy."),
            ],
        }),
        node({
            id: "review-entities",
            label: "Review & Correction",
            lens: "entity",
            kind: "area",
            parent: "entity-model",
            summary: "Polymorphic review items, document graph edges, duplicate candidates, and audit records.",
            details: "These entities describe uncertainty and human correction without turning every review into a task.",
            paths: ["src/doc_intelligence_hub/modules/triage/"],
            tags: ["triage"],
        }),
        node({
            id: "triage-item-entity",
            label: "Needs Review Item",
            lens: "entity",
            kind: "entity",
            parent: "review-entities",
            summary: "A prioritized request for human judgment targeting a document, statement series, or EOB match.",
            details: "The table and APIs call this a Triage Item. Target type and target ID form a polymorphic reference; resolution captures decision, actor, time, and notes.",
            paths: [
                "src/doc_intelligence_hub/modules/triage/database.py",
                "docs/architecture/index.md",
            ],
            tags: ["triage", "polymorphic"],
            stores: [
                store("OWL", "system of record", "/app/data/triage.db: triage_queue", "Priority, source, target, status, and resolution."),
            ],
        }),
        node({
            id: "relationship-entity",
            label: "Document Relationship",
            lens: "entity",
            kind: "entity",
            parent: "review-entities",
            summary: "A typed, directional or symmetric relationship between two Paperless documents.",
            details: "Types include follows, supersedes, supports, and same_sequence. The edge stores provenance, confidence, active state, and priority adjustment.",
            paths: [
                "src/doc_intelligence_hub/modules/triage/database.py",
                "src/doc_intelligence_hub/modules/triage/relationships.py",
            ],
            tags: ["edge", "provenance"],
            stores: [
                store("OWL", "relationship authority", "/app/data/triage.db: document_relationships", "Source and target Paperless IDs, type, provenance, confidence, and review state."),
                store("Paperless-ngx", "endpoint authority", "Paperless documents", "Owns both documents connected by the relationship."),
            ],
        }),
        node({
            id: "duplicate-entity",
            label: "Document Duplicate",
            lens: "entity",
            kind: "entity",
            parent: "review-entities",
            summary: "A candidate duplicate pair with similarity evidence and resolution.",
            details: "Stores two Paperless document IDs, score and breakdown, detection source, status, and merge or rejection decision.",
            paths: [
                "src/doc_intelligence_hub/modules/triage/database.py",
                "src/doc_intelligence_hub/modules/triage/duplicates.py",
            ],
            tags: ["pair", "similarity"],
            stores: [
                store("OWL", "candidate authority", "/app/data/triage.db: document_duplicates", "Similarity evidence and human resolution."),
                store("Paperless-ngx", "document authority", "Paperless documents", "Owns both candidate documents and any final merge operation."),
            ],
        }),
        node({
            id: "correction-event-entity",
            label: "Correction Event",
            lens: "entity",
            kind: "entity",
            parent: "review-entities",
            summary: "Audit record for review, relationship, duplicate, grouping, or metadata changes.",
            details: "Stores event type, target, payload, actor, time, and undo state so the correction history can be explained and reversed where supported.",
            paths: ["src/doc_intelligence_hub/modules/triage/database.py"],
            tags: ["audit", "undo"],
            stores: [
                store("OWL", "system of record", "/app/data/triage.db: correction_events", "Correction history and undo metadata."),
            ],
        }),
        node({
            id: "extraction-correction-entity",
            label: "Extraction Correction",
            lens: "entity",
            kind: "entity",
            parent: "review-entities",
            summary: "A field-level replacement of an extracted value with a user-confirmed value.",
            details: "Preserves the original value, corrected value, field name, source entity, and correction context.",
            paths: ["src/doc_intelligence_hub/modules/triage/database.py"],
            tags: ["field", "feedback"],
            stores: [
                store("OWL", "system of record", "/app/data/triage.db: extraction_corrections", "Original and corrected extracted values."),
            ],
        }),
        node({
            id: "storage-map",
            label: "Physical Stores",
            lens: "entity",
            kind: "root",
            summary: "Where OWL entities and their authoritative source records physically live.",
            details: "Store nodes make split ownership visible. A logical entity can span multiple systems without moving source authority.",
            paths: ["docs/architecture/index.md"],
            tags: ["storage", "ownership"],
        }),
        node({
            id: "paperless-store",
            label: "Paperless Store",
            lens: "entity",
            kind: "store",
            parent: "storage-map",
            summary: "Canonical documents, files, correspondents, tags, document types, fields, and saved views.",
            details: "OWL references Paperless IDs and performs bounded metadata write-back; it does not copy original document authority into SQLite.",
            paths: ["src/doc_intelligence_hub/core/paperless/client.py"],
            tags: ["external", "authority"],
            system: "Paperless-ngx",
        }),
        node({
            id: "statements-store",
            label: "statements.db",
            lens: "entity",
            kind: "store",
            parent: "storage-map",
            summary: "Statement, correspondent, expectation, acquisition, and external-signal state.",
            details: "Owns series and membership, provider and correspondent overlays, document expectations, acquisition sources, external signal generations, and candidates.",
            paths: ["src/doc_intelligence_hub/modules/statements/database.py"],
            tags: ["sqlite"],
        }),
        node({
            id: "action-store",
            label: "action_queue.db",
            lens: "entity",
            kind: "store",
            parent: "storage-map",
            summary: "Action lifecycle, feedback, queue configuration, and processing history.",
            details: "Owns actionable classifier output and its reconciliation metadata.",
            paths: ["src/doc_intelligence_hub/modules/action_queue/database.py"],
            tags: ["sqlite"],
        }),
        node({
            id: "eob-store",
            label: "eob_matching.db",
            lens: "entity",
            kind: "store",
            parent: "storage-map",
            summary: "Extracted EOBs and bills, matches, payments, runs, and audit events.",
            details: "Owns medical-domain derived state keyed back to Paperless documents.",
            paths: ["src/doc_intelligence_hub/modules/eob_matching/database.py"],
            tags: ["sqlite"],
        }),
        node({
            id: "triage-store",
            label: "triage.db",
            lens: "entity",
            kind: "store",
            parent: "storage-map",
            summary: "Needs Review, duplicates, relationships, corrections, and review audit.",
            details: "Owns human-judgment state and the document relationship graph.",
            paths: ["src/doc_intelligence_hub/modules/triage/database.py"],
            tags: ["sqlite"],
        }),
        node({
            id: "alerts-store",
            label: "alerts.db",
            lens: "entity",
            kind: "store",
            parent: "storage-map",
            summary: "Unified alert lifecycle across modules.",
            details: "Modules emit through the shared alerts API instead of reading one another's databases.",
            paths: ["src/doc_intelligence_hub/core/alerts.py"],
            tags: ["sqlite"],
        }),
        node({
            id: "mission-control-store",
            label: "Mission Control Projection",
            lens: "entity",
            kind: "store",
            parent: "storage-map",
            summary: "Bounded projections of OWL actions and alerts for daily work.",
            details: "Projection and experience state are not the source of document intelligence. Mutations reconcile through OWL connector contracts.",
            paths: ["docs/guide/mission-control-integration.md"],
            tags: ["external", "projection"],
            system: "Mission Control",
        }),
        node({
            id: "tyrion-store",
            label: "Tyrion Finance Store",
            lens: "entity",
            kind: "store",
            parent: "storage-map",
            status: "partial",
            summary: "Finance interpretation, policy, attribution, and normalized recurring/account signals.",
            details: "Tyrion can originate bounded document candidates, but current OWL storage does not receive a production reconciliation stream.",
            paths: ["docs/design/active/correspondent-intelligence-and-acquisition.md"],
            tags: ["external", "finance"],
            system: "Tyrion",
        }),
        node({
            id: "monarch-store",
            label: "Monarch",
            lens: "entity",
            kind: "store",
            parent: "storage-map",
            status: "proposed",
            summary: "Authoritative financial transactions, accounts, categories, and recurring obligations.",
            details: "OWL does not currently connect to Monarch. Future financial reconciliation would access bounded facts through Tyrion or its bridge rather than duplicate financial authority.",
            paths: ["docs/feature-roadmap.md"],
            tags: ["external", "future"],
            system: "Monarch",
        }),
    ],
    edges: [
        ["action-queue", "action-entity", "defines", "classifier output"],
        ["statement-tracking", "statement-series-entity", "defines", "recurring grouping"],
        ["correspondent-intelligence", "correspondent-profile-entity", "defines", "OWL policy overlay"],
        ["correspondent-intelligence", "expectation-entity", "defines", "expected document policy"],
        ["eob-matching", "match-entity", "defines", "scored association"],
        ["needs-review", "triage-item-entity", "defines", "human judgment request"],
        ["document-relationships", "relationship-entity", "defines", "typed edge"],
        ["alerts-insights", "alert-entity", "defines", "attention"],
        ["document-views", "document-view-entity", "defines", "safe launch"],
        ["tyrion-signals", "external-candidate-entity", "imports", "bounded signal"],
        ["ocr-quality", "paperless-system", "would version", "approved candidate only"],
        ["financial-reconciliation", "tyrion-system", "would consume", "bounded finance facts"],
        ["financial-reconciliation", "paperless-system", "would link", "source documents"],
        ["mc-connector", "mission-control-system", "projects", "actions and alerts"],
        ["paperless-client", "paperless-system", "reads/writes", "documents and metadata"],
        ["aq-module", "action-store", "owns", "module database"],
        ["statements-module", "statements-store", "owns", "module database"],
        ["eob-module", "eob-store", "owns", "module database"],
        ["triage-module", "triage-store", "owns", "module database"],
        ["alerts-engine", "alerts-store", "owns", "shared alert database"],
        ["aq-module", "alerts-engine", "emits", "action alerts"],
        ["statements-module", "alerts-engine", "emits", "gap alerts"],
        ["eob-module", "alerts-engine", "emits", "match alerts"],
        ["fastapi-app", "react-spa", "serves", "compiled SPA"],
        ["fastapi-app", "domain-layer", "routes", "module APIs"],
        ["domain-layer", "shared-core", "uses", "infrastructure"],
        ["document-entity", "correspondent-entity", "belongs to", "Paperless correspondent"],
        ["document-entity", "metadata-entity", "has", "Paperless fields"],
        ["document-entity", "statement-series-entity", "member of", "series_documents"],
        ["correspondent-entity", "correspondent-profile-entity", "overlaid by", "OWL profile"],
        ["correspondent-profile-entity", "expectation-entity", "owns", "reviewed policy"],
        ["statement-series-entity", "expectation-entity", "bound to", "optional series policy"],
        ["expectation-entity", "acquisition-source-entity", "fulfilled through", "configured source"],
        ["external-candidate-entity", "expectation-entity", "proposes", "requires review"],
        ["external-candidate-entity", "tyrion-store", "sourced from", "finance evidence"],
        ["external-candidate-entity", "mission-control-store", "may transit", "transport only"],
        ["eob-entity", "match-entity", "participates in", "left side"],
        ["bill-entity", "match-entity", "participates in", "right side"],
        ["match-entity", "payment-entity", "tracks", "payment lifecycle"],
        ["match-entity", "match-event-entity", "records", "audit history"],
        ["document-entity", "action-entity", "generates", "classification"],
        ["action-entity", "action-feedback-entity", "receives", "user correction"],
        ["action-entity", "mission-control-store", "projected to", "daily work"],
        ["action-entity", "alert-entity", "may emit", "attention"],
        ["match-entity", "alert-entity", "may emit", "exception"],
        ["statement-series-entity", "alert-entity", "may emit", "missing statement"],
        ["insight-entity", "alert-entity", "may route to", "actionable finding"],
        ["triage-item-entity", "document-entity", "may target", "document"],
        ["triage-item-entity", "statement-series-entity", "may target", "series"],
        ["triage-item-entity", "match-entity", "may target", "match"],
        ["triage-item-entity", "action-entity", "may resolve into", "not always"],
        ["relationship-entity", "document-entity", "connects", "two documents"],
        ["duplicate-entity", "document-entity", "compares", "two documents"],
        ["correction-event-entity", "relationship-entity", "audits", "change"],
        ["correction-event-entity", "duplicate-entity", "audits", "resolution"],
        ["correction-event-entity", "extraction-correction-entity", "audits", "field correction"],
        ["document-view-entity", "paperless-store", "may launch", "saved view"],
        ["document-view-entity", "react-spa", "may launch", "OWL route"],
        ["document-entity", "paperless-store", "stored in", "canonical record"],
        ["metadata-entity", "paperless-store", "stored in", "current values"],
        ["statement-series-entity", "statements-store", "stored in", "series and membership"],
        ["correspondent-profile-entity", "statements-store", "stored in", "profile"],
        ["expectation-entity", "statements-store", "stored in", "policy"],
        ["acquisition-source-entity", "statements-store", "stored in", "source configuration"],
        ["external-candidate-entity", "statements-store", "stored in", "candidate generation"],
        ["eob-entity", "eob-store", "stored in", "extraction"],
        ["bill-entity", "eob-store", "stored in", "extraction"],
        ["match-entity", "eob-store", "stored in", "decision"],
        ["payment-entity", "eob-store", "stored in", "lifecycle"],
        ["action-entity", "action-store", "stored in", "action lifecycle"],
        ["action-feedback-entity", "action-store", "stored in", "feedback"],
        ["triage-item-entity", "triage-store", "stored in", "review queue"],
        ["relationship-entity", "triage-store", "stored in", "document graph"],
        ["duplicate-entity", "triage-store", "stored in", "candidate pair"],
        ["correction-event-entity", "triage-store", "stored in", "audit"],
        ["alert-entity", "alerts-store", "stored in", "alert lifecycle"],
        ["bill-entity", "monarch-store", "future reconciliation", "payment evidence"],
        ["payment-entity", "monarch-store", "future verification", "authoritative transaction"],
    ].map(([source, target, type, label]) => ({ source, target, type, label })),
};
